package engine

import "sort"

// dayLagCoOccurrence counts the days t in [0, T-1-lag] where a is present on
// day t AND b is present on day t+lag. This is a linear (non-circular) count
// over the real observed window — lag near the right edge truncates rather
// than wrapping, which is correct for real calendar data (there is no "day
// after the last day of history").
func dayLagCoOccurrence(a, b []bool, lag int) int {
	T := len(a)
	k := 0
	for t := 0; t+lag < T; t++ {
		if a[t] && b[t+lag] {
			k++
		}
	}
	return k
}

// liftScore is k·T / (n_a·n_b): the ratio of observed lagged co-occurrence to
// the co-occurrence rate expected if a and b's presence were independent
// day-uniform processes. lift == 1 means "no more co-occurrence than raw
// frequency alone predicts" — exactly the popularity-artifact case the
// permutation null and BH-FDR are there to catch. Returns 0 if either
// marginal is 0 (undefined; callers already guard k >= min_support > 0 so
// this only guards a defensive n_a/n_b == 0 that shouldn't occur in practice).
func liftScore(k, T, nA, nB int) float64 {
	if nA == 0 || nB == 0 {
		return 0
	}
	return float64(k) * float64(T) / (float64(nA) * float64(nB))
}

// circularShift rotates presence right by offset days (wrapping), producing a
// new []bool of the same length. shifted[t] = presence[(t-offset+T) mod T].
// Rotation preserves the series' burstiness/autocorrelation and its total
// presence count — it destroys only the alignment with the other series,
// which is exactly what a null model for "is this specific lag alignment
// meaningful" must destroy and nothing else. An IID shuffle would instead
// destroy the autocorrelation itself, making a merely-bursty (but genuinely
// independent) pair look significant — anti-conservative, and gameable.
func circularShift(presence []bool, offset int) []bool {
	T := len(presence)
	if T == 0 {
		return presence
	}
	offset = ((offset % T) + T) % T
	out := make([]bool, T)
	for t := 0; t < T; t++ {
		out[t] = presence[((t-offset)%T+T)%T]
	}
	return out
}

// deterministicShiftOffsets returns n offsets in [1, T-1] for the circular
// null, generated by a deterministic linear-congruential walk rather than
// math/rand or time — required for reproducibility (the same vault + request
// always yields the same p-values). The step is the largest value <= T/2
// that is coprime with T-1, found by decrementing from a fixed starting
// point; coprimality guarantees offsets don't degenerate into a short
// repeating cycle before covering most of the [1, T-1] range at least once.
// When n > T-1 the sequence wraps and repeats — deterministically, and
// documented: production default N=500 against a 365-day window (T-1=364)
// does not wrap.
func deterministicShiftOffsets(T, n int) []int {
	offsets := make([]int, n)
	if T <= 1 {
		return offsets // all zero; caller's dayLagCoOccurrence degenerates gracefully
	}
	modulus := T - 1
	if modulus <= 0 {
		modulus = 1
	}
	step := modulus / 2
	if step < 1 {
		step = 1
	}
	for gcd(step, modulus) != 1 && step > 1 {
		step--
	}
	for i := 0; i < n; i++ {
		offsets[i] = 1 + (i*step)%modulus
	}
	return offsets
}

func gcd(a, b int) int {
	for b != 0 {
		a, b = b, a%b
	}
	if a < 0 {
		return -a
	}
	return a
}

// circularShiftPValue draws len(offsets) circular-shift permutations of b,
// recomputes lift for each, and returns the permutation p-value: the
// (add-one-smoothed) fraction of null lifts at or above the observed lift.
// The +1 in both numerator and denominator is the standard permutation-test
// correction (Davison & Hinkley) that guarantees p > 0 even when zero of N
// draws exceed the observed statistic — reporting p=0 from a finite sample
// would overstate the evidence.
func circularShiftPValue(a, b []bool, lag, T, nA int, offsets []int, observedLift float64) float64 {
	nB := 0
	for _, v := range b {
		if v {
			nB++
		}
	}
	exceed := 0
	for _, offset := range offsets {
		shifted := circularShift(b, offset)
		k := dayLagCoOccurrence(a, shifted, lag)
		nullLift := liftScore(k, T, nA, nB)
		if nullLift >= observedLift {
			exceed++
		}
	}
	return float64(exceed+1) / float64(len(offsets)+1)
}

// benjaminiHochberg computes BH-FDR q-values for a slice of p-values.
// q-values are computed over the ENTIRE input slice (every test performed
// that met the support floor), not just candidates that already look
// significant — FDR-ing only the survivors is p-hacking and is explicitly
// forbidden by the design. Returns q-values in the same order as pvals.
func benjaminiHochberg(pvals []float64) []float64 {
	m := len(pvals)
	q := make([]float64, m)
	if m == 0 {
		return q
	}
	type indexed struct {
		p   float64
		idx int
	}
	sorted := make([]indexed, m)
	for i, p := range pvals {
		sorted[i] = indexed{p: p, idx: i}
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].p < sorted[j].p })

	adj := make([]float64, m)
	for rank := m; rank >= 1; rank-- {
		s := sorted[rank-1]
		raw := s.p * float64(m) / float64(rank)
		if raw > 1 {
			raw = 1
		}
		if rank == m {
			adj[rank-1] = raw
		} else {
			// Monotonicity: q must be non-decreasing as p increases (standard
			// BH step-up procedure — enforce via the running minimum from the
			// top p-value down).
			if raw < adj[rank] {
				adj[rank-1] = raw
			} else {
				adj[rank-1] = adj[rank]
			}
		}
	}
	for rank, s := range sorted {
		q[s.idx] = adj[rank]
	}
	return q
}
